### PR TITLE
fix(Makefile): add a glideup build target

### LINKED ISSUE #58: add a 'glideup' build target to the makefile
something to run `glide up` inside the dev container

### PR DESCRIPTION
**Pull request by arschles**
Fixes #58

### CODE REVIEW

**Comment by bacongobbler** [comment]
isn't `make bootstrap` the equivalent? From `glide --help`:

```
update, up, install          Update or install a project's dependencies
```

**Comment by arschles** [comment]
@bacongobbler don't believe so.

According to [the `update` documentation](https://github.com/masterminds/glide#glide-update-aliased-to-up): `Download or update all of the libraries listed in the glide.yaml file ... A glide.lock file will be created or updated with the dependencies pinned to specific versions`.

And, according to [the `install` documentation](https://github.com/masterminds/glide#glide-install): `This will read the glide.lock file, making sure it's tied to the glide.yaml file, and install the commit id specific versions there ... When the glide.lock file doesn't tie to the glide.yaml file, such as there being a change, it will provide an error. Running glide up will recreate the glide.lock file when updating the dependency tree.`

Also, based on my experience so far, `glide up` has two major differences from `install`:
1. If you've changed your `glide.yaml` file, you can run it to regenerate your `glide.lock` file
2. If you've specified a dependency, but no specific version, in your `glide.yaml`, you can run `glide update` to update its version in the `glide.lock`

**Comment by bacongobbler** [comment]
gotcha. I'm okay with this since it doesn't affect anything else.

**Comment by arschles** [comment]
thanks @bacongobbler

**Pull request merged**
