### PR TITLE
fix(*): build and run the server inside alpine:3.3 (WIP)

### LINKED ISSUE #8: use alpine:3.2 in the docker image
currently using `ubuntu-debootstrap:14.04`

### PR DESCRIPTION
**Pull request by arschles**
Fixes #8

### CODE REVIEW

**Comment by arschles** [comment]
this is untested in production

**Comment by arschles** [comment]
removing both LGTMs - current status of this PR is that the minio server fails to start with `sh: minio: not found`

**Comment by arschles** [comment]
removing the `v2-beta` milestone since this isn't critical for the release

**Comment by mboersma** [comment]
Just to note: deis/minio currently builds minio [from source](https://github.com/deis/minio/blob/master/server/install.sh#L17) using commit SHA [356b889](https://github.com/minio/minio/commit/356b889). When we previously had tried to move to an official release tag, we saw problems in testing and reverted. This was months ago, so it's probably worth revisiting updated minio releases and/or binary builds.

**Comment by arschles** [comment]
@mboersma thanks for the context. I'm putting this on the v2 milestone so we can try again, and I'll rebase now

**Comment by arschles** [comment]
Oops, actually this PR is obsoleted by #98, which has moved minio to run in ubuntu-slim. Closing.

Also, using binary builds is tracked in https://github.com/deis/minio/issues/87

**Pull request closed without merging**
