### PR TITLE
feat(secret): use objectstorage secret for creds than minio user secret

### PR DESCRIPTION
**Pull request by kmala**

### CODE REVIEW

**Comment by bacongobbler** [comment]
I guess we'll also need to update workflow-dev to remove the minio-user secret with this change. Is there another PR for that, or are you currently working on that one as well?

**Comment by bacongobbler** [comment]
Triaging for v2.0-beta2.

**Comment by kmala** [comment]
requires https://github.com/deis/charts/pull/221 and #89

**Comment by kmala** [comment]
punting to beta4 as it depends on helm side change

**Comment by jchauncey** [comment]
@kmala where are we at with this?

**Comment by kmala** [comment]
@jchauncey this depends on the https://github.com/deis/charts/pull/221

**Pull request merged**
